version: '3.8'

services:
  reactstream-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reactstream-app
    ports:
      - "${SERVER_PORT:-80}:${SERVER_PORT:-80}"
      - "${DEV_SERVER_PORT:-3010}:${DEV_SERVER_PORT:-3010}"
    volumes:
      - ./components:/app/components
      - ./logs:/app/logs
      - ./temp:/app/temp
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - VIRTUAL_HOST=${VIRTUAL_HOST:-www.reactstream.com}
    restart: unless-stopped
    networks:
      - reactstream-network

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - reactstream-network

networks:
  reactstream-network:
    driver: bridge
